$(document).ready(function(){
  $('.BBC_wrapper').mouseover(function(){
                           $('.BBC').hide();
                           $('.BBC_desc_wrapper').show();
                         });
  $('.BBC_wrapper').mouseout(function(){
                           $('.BBC_desc_wrapper').hide();
                           $('.BBC').show();
                         });
  $('.BA_wrapper').mouseover(function(){
                           $('.BA').hide();
                           $('.BA_desc_wrapper').show();
                         });
  $('.BA_wrapper').mouseout(function(){
                           $('.BA_desc_wrapper').hide();
                           $('.BA').show();
                         });
  $('.PHILIPS_wrapper').mouseover(function(){
                           $('.PHILIPS').hide();
                           $('.PHILIPS_desc_wrapper').show();
                         });
  $('.PHILIPS_wrapper').mouseout(function(){
                           $('.PHILIPS_desc_wrapper').hide();
                           $('.PHILIPS').show();
                         });
  $('.COKE_wrapper').mouseover(function(){
                           $('.COKE').hide();
                           $('.COKE_desc_wrapper').show();
                         });
  $('.COKE_wrapper').mouseout(function(){
                           $('.COKE_desc_wrapper').hide();
                           $('.COKE').show();
                         });
  $('.BUPA_wrapper').mouseover(function(){
                           $('.BUPA').hide();
                           $('.BUPA_desc_wrapper').show();
                         });
  $('.BUPA_wrapper').mouseout(function(){
                           $('.BUPA_desc_wrapper').hide();
                           $('.BUPA').show();
                         });
  $('.SAMSUNG_wrapper').mouseover(function(){
                           $('.SAMSUNG').hide();
                           $('.SAMSUNG_desc_wrapper').show();
                         });
  $('.SAMSUNG_wrapper').mouseout(function(){
                           $('.SAMSUNG_desc_wrapper').hide();
                           $('.SAMSUNG').show();
                         });
  $('.MTV_wrapper').mouseover(function(){
                           $('.MTV').hide();
                           $('.MTV_desc_wrapper').show();
                         });
  $('.MTV_wrapper').mouseout(function(){
                           $('.MTV_desc_wrapper').hide();
                           $('.MTV').show();
                         });
  $('.MICROSOFT_wrapper').mouseover(function(){
                           $('.MICROSOFT').hide();
                           $('.MICROSOFT_desc_wrapper').show();
                         });
  $('.MICROSOFT_wrapper').mouseout(function(){
                           $('.MICROSOFT_desc_wrapper').hide();
                           $('.MICROSOFT').show();
                         });
  $('.SKY_wrapper').mouseover(function(){
                           $('.SKY').hide();
                           $('.SKY_desc_wrapper').show();
                         });
  $('.SKY_wrapper').mouseout(function(){
                           $('.SKY_desc_wrapper').hide();
                           $('.SKY').show();
                         });
});