$(document).ready(function(){
  $('.analytics_wrapper').mouseover(function(){
                           $('.analytics').hide();
                           $('.analytics_desc_wrapper').show();
                         });
  $('.analytics_wrapper').mouseout(function(){
                           $('.analytics_desc_wrapper').hide();
                           $('.analytics').show();
                         });
  $('.insight_wrapper').mouseover(function(){
                           $('.insight').hide();
                           $('.insight_desc_wrapper').show();
                         });
  $('.insight_wrapper').mouseout(function(){
                           $('.insight_desc_wrapper').hide();
                           $('.insight').show();
                         });
  $('.strategy_wrapper').mouseover(function(){
                           $('.strategy').hide();
                           $('.strategy_desc_wrapper').show();
                         });
  $('.strategy_wrapper').mouseout(function(){
                           $('.strategy_desc_wrapper').hide();
                           $('.strategy').show();
                         });
  $('.planning_wrapper').mouseover(function(){
                           $('.planning').hide();
                           $('.planning_desc_wrapper').show();
                         });
  $('.planning_wrapper').mouseout(function(){
                           $('.planning_desc_wrapper').hide();
                           $('.planning').show();
                         });
  $('.design_wrapper').mouseover(function(){
                           $('.design').hide();
                           $('.design_desc_wrapper').show();
                         });
  $('.design_wrapper').mouseout(function(){
                           $('.design_desc_wrapper').hide();
                           $('.design').show();
                         });
  $('.management_wrapper').mouseover(function(){
                           $('.management').hide();
                           $('.management_desc_wrapper').show();
                         });
  $('.management_wrapper').mouseout(function(){
                           $('.management_desc_wrapper').hide();
                           $('.management').show();
                         });
  });